/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package belajar_checklist;

import javax.swing.JOptionPane;

/**
 *
 * @author revan
 */
public class jfCheckLIst extends javax.swing.JFrame {
    int hrgoli, hrgrem, hrgser, total, beli, totoli;

    /**
     * Creates new form jfCheckLIst
     */
    public jfCheckLIst() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jchkoli = new javax.swing.JCheckBox();
        jchkser = new javax.swing.JCheckBox();
        jchkrem = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtrem = new javax.swing.JTextField();
        jbBersih = new javax.swing.JButton();
        jbKeluar = new javax.swing.JButton();
        jtxtoli = new javax.swing.JTextField();
        jtxtser = new javax.swing.JTextField();
        jtxttotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jchkoli.setText("Ganti Oli");
        jchkoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkoliActionPerformed(evt);
            }
        });

        jchkser.setText("Service Lengkap");
        jchkser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkserActionPerformed(evt);
            }
        });

        jchkrem.setText("Canvas Rem");
        jchkrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkremActionPerformed(evt);
            }
        });

        jLabel1.setText("Bengkel Ogah Rugi");

        jLabel2.setText("Total");

        jbBersih.setText("Bersih");
        jbBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBersihActionPerformed(evt);
            }
        });

        jbKeluar.setText("Keluar");
        jbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbBersih)
                        .addGap(112, 112, 112)
                        .addComponent(jbKeluar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtoli, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jchkser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jchkrem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jchkoli, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtrem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtoli, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkoli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkser)
                    .addComponent(jtxtser, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkrem)
                    .addComponent(jtxtrem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBersih)
                    .addComponent(jbKeluar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchkserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkserActionPerformed
        if(jchkser.isSelected())
        {
            hrgser=50000;
            total=hrgoli+hrgrem+hrgser;
            jtxtser.setText(String.valueOf(hrgser));
            jtxttotal.setText(String.valueOf(total));
        }
        else
        {
            hrgser=0;
            total=hrgoli+hrgrem+hrgser;
            jtxtser.setText(String.valueOf(hrgser));
            jtxttotal.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_jchkserActionPerformed

    private void jchkoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkoliActionPerformed
        if(jchkoli.isSelected())
        {
            hrgoli=27000;
            total=hrgoli+hrgrem+hrgser;
            jtxtoli.setText(String.valueOf(hrgoli));
            jtxttotal.setText(String.valueOf(total));
        }
        else
        {
            hrgoli=0;
            total=hrgoli+hrgrem+hrgser;
            jtxtoli.setText(String.valueOf(hrgoli));
            jtxttotal.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_jchkoliActionPerformed

    private void jchkremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkremActionPerformed
        if(jchkrem.isSelected())
        {
            hrgrem=30000;
            total=hrgoli+hrgrem+hrgser;
            jtxtrem.setText(String.valueOf(hrgrem));
            jtxttotal.setText(String.valueOf(total));
        }
        else
        {
            hrgrem=0;
            total=hrgoli+hrgrem+hrgser;
            jtxtrem.setText(String.valueOf(hrgrem));
            jtxttotal.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_jchkremActionPerformed

    private void jbBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBersihActionPerformed
        jchkoli.setSelected(false);
        jchkrem.setSelected(false);
        jchkser.setSelected(false);
        jtxtoli.setText("");
        jtxtrem.setText("");
        jtxtser.setText("");
        jtxttotal.setText("");
        hrgoli=0;hrgrem=0;hrgser=0;total=0;
    }//GEN-LAST:event_jbBersihActionPerformed

    private void jbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKeluarActionPerformed
        int answer = JOptionPane.showConfirmDialog(null,"Yakin Mau Keluar Dari Form ini..?","Informasi",JOptionPane.YES_NO_OPTION);
        if(answer==JOptionPane.YES_OPTION){
        dispose();
        }
    }//GEN-LAST:event_jbKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfCheckLIst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfCheckLIst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfCheckLIst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfCheckLIst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfCheckLIst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbBersih;
    private javax.swing.JButton jbKeluar;
    private javax.swing.JCheckBox jchkoli;
    private javax.swing.JCheckBox jchkrem;
    private javax.swing.JCheckBox jchkser;
    private javax.swing.JTextField jtxtoli;
    private javax.swing.JTextField jtxtrem;
    private javax.swing.JTextField jtxtser;
    private javax.swing.JTextField jtxttotal;
    // End of variables declaration//GEN-END:variables
}
